### ISSUE TITLE
proper way to get dimensions of surfaces?

### ISSUE THREAD

**Issue by konsumer** [littledivy/deno_sdl2#32]
I couldn't figure out how to get the dimensions of images & fonts.

I am currently doing this:

```ts
const imgTitle = {
  tex: canvas.createTextureFromSurface(canvas.loadSurface('./assets/title.png')),
  dim: { x: 0, y: 0, width: 158, height: 62  }
}

// ...later
const pos = { ...imgTitle.dim, x: 80, y: 60}
canvas.copy(imgTitle.tex, imgTitle.dim, pos)

```

where I just put in the right size

and

```ts
canvas.renderFont(font, "Press any key.", {
    blended: { color: { r: 255, g: 255, b: 255, a: 255 } },
  }, {
    x: 120,
    y: 130,
    width: 80,
    height: 14,
  })
```

where I guess, and tweak it until it sort of fits.

Is there a proper way to do this that can tell me the size of some text used by a font, or would there be interest in adding some utilities like this in a PR?

I am imagining things like [love has](https://love2d.org/wiki/Font). `getLineHeight` and `getWrap` and `getWidth` are super-useful for laying out text.

Seems like [TTF_SizeText](https://rust-sdl2.github.io/rust-sdl2/sdl2_sys/ttf/fn.TTF_SizeText.html) might be a good start, but I'm not sure how to wrap it in deno/deno_sdl2.

**Comment by littledivy** [comment]
Not passing `width` and `height` will set a suitable height/width for your font based on `SDL_QueryTexture()`. 

Making this available to the user will be a little tricky since we don't really have a "query" mechanism in place to request resource information from Rust.

I'm happy to accept PRs adding this mechanism along with bindings to `SDL_QueryTexture` for the loaded font which is already being tracked in #25

**Comment by konsumer** [comment]
> Not passing width and height will set a suitable height/width for your font based on SDL_QueryTexture()

I get this error, leaving it off:
```
error: TS2345 [ERROR]: Argument of type '{ x: number; y: number; }' is not assignable to parameter of type 'Rect'.
```

```ts
canvas.renderFont(font, "Press any key.", {
      blended: { color: { r: 255, g: 255, b: 255, a: 255 } },
    }, {
      x: 120,
      y: 130
    })
```

> Making this available to the user will be a little tricky since we don't really have a "query" mechanism in place to request resource information from Rust.

I'm not quite sure how to approach it. If I understand the code, it downloads a rust-compiled runtime that starts a socket on port 34254, and reads incoming JSON messages, turning them into operations, with no return values. How would it work?

> I'm happy to accept PRs adding this mechanism along with bindings to SDL_QueryTexture for the loaded font which is already being tracked in #25

Sounds good. I will dig in and see if I can figure it out.

**Comment by littledivy** [comment]
Ah! `renderFont` types are wrong. I'll fix it, meanwhile it should work with `// @ts-ignore`
