### ISSUE TITLE
SDL2 fails to create a windows surface with Deno 2.0

### ISSUE THREAD

**Issue by heretique** [littledivy/deno_sdl2#80]
Hi, I was using SDL2 module with Deno to play around with native windows and WebGPU.
Repository here: https://github.com/heretique/deno-native-webgpu-playground
This has stopped working with Deno 2.0. I'm getting this error on Windows 11:
```
SDL2 initialized on Windows
error: Uncaught (in promise) TypeError: options must be provided.
        return new Deno.UnsafeWindowSurface("win32", window, hinstance);
               ^
    at new UnsafeWindowSurface (ext:deno_webgpu/02_surface.js:184:13)
    at Window.windowSurface (https://deno.land/x/sdl2@0.9.0/mod.ts:1274:16)
    at file:///C:/Workspace/DenoProjects/deno-native-webgpu-playground/examples/cube.ts:25:24
```

**Comment by heretique** [comment]
And a similar error Linux Mint:
```
SDL2 initialized on Linux
error: Uncaught (in promise) TypeError: options must be provided.
        return new Deno.UnsafeWindowSurface("x11", window, display);
               ^
    at new UnsafeWindowSurface (ext:deno_webgpu/02_surface.js:184:13)
    at Window.windowSurface (https://deno.land/x/sdl2@0.9.0/mod.ts:1290:16)
    at file:///home/cata/Workspace/DenoProjects/deno-native-webgpu-playground/examples/cube.ts:25:24
```

**Comment by littledivy** [comment]
Please upgrade to latest version `0.14`

**Comment by heretique** [comment]
Ah, I haven't notice that the module moved to JSR, maybe you could add a comment on [deno.land](https://deno.land/x/sdl2) that the module moved to JSR because if I search for `deno sdl2` that's the first result I get, JSR page doesn't show up.

![image](https://github.com/user-attachments/assets/81cfa5e1-ed0e-4137-bc79-2d28efc80260)

After switching to JSR and version `0.14` I still got at first an error
```
error: Uncaught (in promise) TypeError: width and height must be provided.
```
But then I noticed that the `Windows.windowSurface` got two new parameters, `width` and `height`. Adding those changes makes it work again

![image](https://github.com/user-attachments/assets/0eb5763b-e3d0-4477-841d-f68c0e79472d)

Thank you @littledivy
